version: '3.8'

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: ""               # <-- Empty string since root has no password
      DB_NAME: tertibega_coffee

  db:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: tertibega_coffee
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
